/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.4.1 on 2014-10-24 21:03:25,
 any modifications will be overwritten.
 ==============================================================
 */

package org.eclipse.m2e.core.internal.lifecyclemapping.model;

/**
 * Class LifecycleMappingMetadata.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class LifecycleMappingMetadata
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field packagingType.
     */
    private String packagingType;

    /**
     * Field lifecycleMappingId.
     */
    private String lifecycleMappingId;

    /**
     * Field lifecycleMappingVersionRange.
     */
    private String lifecycleMappingVersionRange;

    /**
     * Field pluginExecutions.
     */
    private java.util.List<PluginExecutionMetadata> pluginExecutions;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addPluginExecution.
     * 
     * @param pluginExecutionMetadata
     */
    public void addPluginExecution( PluginExecutionMetadata pluginExecutionMetadata )
    {
        getPluginExecutions().add( pluginExecutionMetadata );
    } //-- void addPluginExecution( PluginExecutionMetadata )

    /**
     * Get the lifecycleMappingId field.
     * 
     * @return String
     */
    public String getLifecycleMappingId()
    {
        return this.lifecycleMappingId;
    } //-- String getLifecycleMappingId()

    /**
     * Get the lifecycleMappingVersionRange field.
     * 
     * @return String
     */
    public String getLifecycleMappingVersionRange()
    {
        return this.lifecycleMappingVersionRange;
    } //-- String getLifecycleMappingVersionRange()

    /**
     * Get the packagingType field.
     * 
     * @return String
     */
    public String getPackagingType()
    {
        return this.packagingType;
    } //-- String getPackagingType()

    /**
     * Method getPluginExecutions.
     * 
     * @return List
     */
    public java.util.List<PluginExecutionMetadata> getPluginExecutions()
    {
        if ( this.pluginExecutions == null )
        {
            this.pluginExecutions = new java.util.ArrayList<PluginExecutionMetadata>();
        }

        return this.pluginExecutions;
    } //-- java.util.List<PluginExecutionMetadata> getPluginExecutions()

    /**
     * Method removePluginExecution.
     * 
     * @param pluginExecutionMetadata
     */
    public void removePluginExecution( PluginExecutionMetadata pluginExecutionMetadata )
    {
        getPluginExecutions().remove( pluginExecutionMetadata );
    } //-- void removePluginExecution( PluginExecutionMetadata )

    /**
     * Set the lifecycleMappingId field.
     * 
     * @param lifecycleMappingId
     */
    public void setLifecycleMappingId( String lifecycleMappingId )
    {
        this.lifecycleMappingId = lifecycleMappingId;
    } //-- void setLifecycleMappingId( String )

    /**
     * Set the lifecycleMappingVersionRange field.
     * 
     * @param lifecycleMappingVersionRange
     */
    public void setLifecycleMappingVersionRange( String lifecycleMappingVersionRange )
    {
        this.lifecycleMappingVersionRange = lifecycleMappingVersionRange;
    } //-- void setLifecycleMappingVersionRange( String )

    /**
     * Set the packagingType field.
     * 
     * @param packagingType
     */
    public void setPackagingType( String packagingType )
    {
        this.packagingType = packagingType;
    } //-- void setPackagingType( String )

    /**
     * Set the pluginExecutions field.
     * 
     * @param pluginExecutions
     */
    public void setPluginExecutions( java.util.List<PluginExecutionMetadata> pluginExecutions )
    {
        this.pluginExecutions = pluginExecutions;
    } //-- void setPluginExecutions( java.util.List )

    
  private transient LifecycleMappingMetadataSource source;
  public void setSource(LifecycleMappingMetadataSource source) {
    this.source = source;
  }
  public LifecycleMappingMetadataSource getSource() {
    return this.source;
  }
            
          
}
