/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.4.1 on 2014-10-24 21:03:25,
 any modifications will be overwritten.
 ==============================================================
 */

package org.eclipse.m2e.core.internal.lifecyclemapping.model;

/**
 * Class LifecycleMappingMetadataSource.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class LifecycleMappingMetadataSource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field groupId.
     */
    private String groupId;

    /**
     * Field artifactId.
     */
    private String artifactId;

    /**
     * Field version.
     */
    private String version;

    /**
     * Field lifecycleMappings.
     */
    private java.util.List<LifecycleMappingMetadata> lifecycleMappings;

    /**
     * Field pluginExecutions.
     */
    private java.util.List<PluginExecutionMetadata> pluginExecutions;

    /**
     * Field modelEncoding.
     */
    private String modelEncoding = "UTF-8";


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addLifecycleMapping.
     * 
     * @param lifecycleMappingMetadata
     */
    public void addLifecycleMapping( LifecycleMappingMetadata lifecycleMappingMetadata )
    {
        getLifecycleMappings().add( lifecycleMappingMetadata );
    } //-- void addLifecycleMapping( LifecycleMappingMetadata )

    /**
     * Method addPluginExecution.
     * 
     * @param pluginExecutionMetadata
     */
    public void addPluginExecution( PluginExecutionMetadata pluginExecutionMetadata )
    {
        getPluginExecutions().add( pluginExecutionMetadata );
    } //-- void addPluginExecution( PluginExecutionMetadata )

    /**
     * Get the artifactId field.
     * 
     * @return String
     */
    public String getArtifactId()
    {
        return this.artifactId;
    } //-- String getArtifactId()

    /**
     * Get the groupId field.
     * 
     * @return String
     */
    public String getGroupId()
    {
        return this.groupId;
    } //-- String getGroupId()

    /**
     * Method getLifecycleMappings.
     * 
     * @return List
     */
    public java.util.List<LifecycleMappingMetadata> getLifecycleMappings()
    {
        if ( this.lifecycleMappings == null )
        {
            this.lifecycleMappings = new java.util.ArrayList<LifecycleMappingMetadata>();
        }

        return this.lifecycleMappings;
    } //-- java.util.List<LifecycleMappingMetadata> getLifecycleMappings()

    /**
     * Get the modelEncoding field.
     * 
     * @return String
     */
    public String getModelEncoding()
    {
        return this.modelEncoding;
    } //-- String getModelEncoding()

    /**
     * Method getPluginExecutions.
     * 
     * @return List
     */
    public java.util.List<PluginExecutionMetadata> getPluginExecutions()
    {
        if ( this.pluginExecutions == null )
        {
            this.pluginExecutions = new java.util.ArrayList<PluginExecutionMetadata>();
        }

        return this.pluginExecutions;
    } //-- java.util.List<PluginExecutionMetadata> getPluginExecutions()

    /**
     * Get the version field.
     * 
     * @return String
     */
    public String getVersion()
    {
        return this.version;
    } //-- String getVersion()

    /**
     * Method removeLifecycleMapping.
     * 
     * @param lifecycleMappingMetadata
     */
    public void removeLifecycleMapping( LifecycleMappingMetadata lifecycleMappingMetadata )
    {
        getLifecycleMappings().remove( lifecycleMappingMetadata );
    } //-- void removeLifecycleMapping( LifecycleMappingMetadata )

    /**
     * Method removePluginExecution.
     * 
     * @param pluginExecutionMetadata
     */
    public void removePluginExecution( PluginExecutionMetadata pluginExecutionMetadata )
    {
        getPluginExecutions().remove( pluginExecutionMetadata );
    } //-- void removePluginExecution( PluginExecutionMetadata )

    /**
     * Set the artifactId field.
     * 
     * @param artifactId
     */
    public void setArtifactId( String artifactId )
    {
        this.artifactId = artifactId;
    } //-- void setArtifactId( String )

    /**
     * Set the groupId field.
     * 
     * @param groupId
     */
    public void setGroupId( String groupId )
    {
        this.groupId = groupId;
    } //-- void setGroupId( String )

    /**
     * Set the lifecycleMappings field.
     * 
     * @param lifecycleMappings
     */
    public void setLifecycleMappings( java.util.List<LifecycleMappingMetadata> lifecycleMappings )
    {
        this.lifecycleMappings = lifecycleMappings;
    } //-- void setLifecycleMappings( java.util.List )

    /**
     * Set the modelEncoding field.
     * 
     * @param modelEncoding
     */
    public void setModelEncoding( String modelEncoding )
    {
        this.modelEncoding = modelEncoding;
    } //-- void setModelEncoding( String )

    /**
     * Set the pluginExecutions field.
     * 
     * @param pluginExecutions
     */
    public void setPluginExecutions( java.util.List<PluginExecutionMetadata> pluginExecutions )
    {
        this.pluginExecutions = pluginExecutions;
    } //-- void setPluginExecutions( java.util.List )

    /**
     * Set the version field.
     * 
     * @param version
     */
    public void setVersion( String version )
    {
        this.version = version;
    } //-- void setVersion( String )

    
  private transient Object source;
  public void setSource(Object source) {
    this.source = source;
  }
  public Object getSource() {
    return this.source;
  }
            
          
}
